# Generated by Django 5.0.4 on 2025-04-26 00:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_rename_total_amount_invoice_subtotal_and_more"),
        ("cases", "0002_court_practicearea_alter_case_options_and_more"),
        ("clients", "0003_alter_client_options_client_address_line1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Activity Code",
                "verbose_name_plural": "Activity Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Tax",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expense_receipts/",
                        verbose_name="Receipt",
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(default=True, verbose_name="Billable"),
                ),
                (
                    "is_billed",
                    models.BooleanField(default=False, verbose_name="Billed"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, verbose_name="Billable by Default"
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrustAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Account Number"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Trust Account",
                "verbose_name_plural": "Trust Accounts",
            },
        ),
        migrations.CreateModel(
            name="TrustTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal")],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference Number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Trust Transaction",
                "verbose_name_plural": "Trust Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="timeentry",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Discount",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Tax Rate %",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("TIME", "Time Entry"),
                    ("EXPENSE", "Expense"),
                    ("FLAT_FEE", "Flat Fee"),
                    ("OTHER", "Other"),
                ],
                default="TIME",
                max_length=10,
                verbose_name="Item Type",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="time_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="billing.timeentry",
                verbose_name="Time Entry",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Received By",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference Number"
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="billing_status",
            field=models.CharField(
                choices=[
                    ("BILLABLE", "Billable"),
                    ("NON_BILLABLE", "Non-Billable"),
                    ("NO_CHARGE", "No Charge"),
                ],
                default="BILLABLE",
                max_length=20,
                verbose_name="Billing Status",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeentry",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="is_billed",
            field=models.BooleanField(default=False, verbose_name="Billed"),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start Time"),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="cases.case",
                verbose_name="Case",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(verbose_name="Due Date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Invoice Number"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(verbose_name="Issue Date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partially Paid"),
                    ("OVERDUE", "Overdue"),
                    ("VOID", "Void"),
                ],
                default="DRAFT",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Tax Amount",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Rate"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CHECK", "Check"),
                    ("CREDIT_CARD", "Credit Card"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CASH", "Cash"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="cases.case",
                verbose_name="Case",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="hours",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Hours"
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="is_billable",
            field=models.BooleanField(default=True, verbose_name="Billable"),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Rate"
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Timekeeper",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="activity_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="billing.activitycode",
                verbose_name="Activity Code",
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["case", "-date"], name="billing_tim_case_id_06315e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["user", "-date"], name="billing_tim_user_id_7d414e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["is_billed"], name="billing_tim_is_bill_7bab33_idx"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="cases.case",
                verbose_name="Case",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="billing.expense",
                verbose_name="Expense",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="billing.expensecategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="trustaccount",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_accounts",
                to="clients.client",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="trusttransaction",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_transactions",
                to="cases.case",
                verbose_name="Case",
            ),
        ),
        migrations.AddField(
            model_name="trusttransaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_trust_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="trusttransaction",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_transactions",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="trusttransaction",
            name="trust_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="billing.trustaccount",
                verbose_name="Trust Account",
            ),
        ),
    ]
