# Generated by Django 5.0.4 on 2025-04-26 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
        ("clients", "0003_alter_client_options_client_address_line1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "jurisdiction",
                    models.CharField(max_length=100, verbose_name="Jurisdiction"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Court",
                "verbose_name_plural": "Courts",
                "ordering": ["jurisdiction", "name"],
            },
        ),
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Practice Area",
                "verbose_name_plural": "Practice Areas",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["-open_date"],
                "permissions": [
                    ("close_case", "Can close a case"),
                    ("reopen_case", "Can reopen a case"),
                    ("assign_case", "Can assign a case to users"),
                ],
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
            },
        ),
        migrations.AlterModelOptions(
            name="casenote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Case Note",
                "verbose_name_plural": "Case Notes",
            },
        ),
        migrations.RemoveField(
            model_name="case",
            name="assigned_lawyer",
        ),
        migrations.AddField(
            model_name="case",
            name="assigned_attorney",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attorney_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Attorney",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="assigned_paralegal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paralegal_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Paralegal",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="billing_method",
            field=models.CharField(
                choices=[
                    ("HOURLY", "Hourly"),
                    ("FLAT_FEE", "Flat Fee"),
                    ("CONTINGENCY", "Contingency"),
                    ("PRO_BONO", "Pro Bono"),
                ],
                default="HOURLY",
                max_length=20,
                verbose_name="Billing Method",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="court_case_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Court Case Number"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="internal_reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Internal Reference"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="is_billable",
            field=models.BooleanField(default=True, verbose_name="Billable"),
        ),
        migrations.AddField(
            model_name="case",
            name="judge",
            field=models.CharField(blank=True, max_length=100, verbose_name="Judge"),
        ),
        migrations.AddField(
            model_name="case",
            name="opposing_counsel",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Opposing Counsel"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="MEDIUM",
                max_length=10,
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="retainer_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Retainer Amount",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="statute_of_limitations",
            field=models.DateField(
                blank=True, null=True, verbose_name="Statute of Limitations"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="casenote",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Private notes are only visible to staff, not clients",
                verbose_name="Private",
            ),
        ),
        migrations.AddField(
            model_name="casenote",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Case Number"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("CIVIL_LITIGATION", "Civil Litigation"),
                    ("CRIMINAL_DEFENSE", "Criminal Defense"),
                    ("CORPORATE", "Corporate"),
                    ("FAMILY", "Family Law"),
                    ("ESTATE", "Estate Planning"),
                    ("REAL_ESTATE", "Real Estate"),
                    ("INTELLECTUAL_PROPERTY", "Intellectual Property"),
                    ("IMMIGRATION", "Immigration"),
                    ("BANKRUPTCY", "Bankruptcy"),
                    ("PERSONAL_INJURY", "Personal Injury"),
                    ("EMPLOYMENT", "Employment"),
                    ("TAX", "Tax"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                verbose_name="Case Type",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="clients.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="close_date",
            field=models.DateField(blank=True, null=True, verbose_name="Close Date"),
        ),
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="case",
            name="open_date",
            field=models.DateField(auto_now_add=True, verbose_name="Open Date"),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PENDING", "Pending"),
                    ("DISCOVERY", "Discovery"),
                    ("TRIAL", "Trial"),
                    ("APPEAL", "Appeal"),
                    ("SETTLED", "Settled"),
                    ("CLOSED", "Closed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="OPEN",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="casenote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="casenote",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="cases.case",
                verbose_name="Case",
            ),
        ),
        migrations.AlterField(
            model_name="casenote",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="casenote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="casenote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.CreateModel(
            name="CaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("COURT_DATE", "Court Date"),
                            ("FILING", "Filing"),
                            ("DEADLINE", "Deadline"),
                            ("MEETING", "Meeting"),
                            ("DEPOSITION", "Deposition"),
                            ("COMMUNICATION", "Communication"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Time")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(default=False, verbose_name="Critical"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cases.case",
                        verbose_name="Case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Event",
                "verbose_name_plural": "Case Events",
                "ordering": ["date", "time"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="cases.court",
                verbose_name="Court",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="practice_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="cases.practicearea",
                verbose_name="Practice Area",
            ),
        ),
        migrations.CreateModel(
            name="CaseTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD_ATTORNEY", "Lead Attorney"),
                            ("ATTORNEY", "Attorney"),
                            ("PARALEGAL", "Paralegal"),
                            ("LEGAL_ASSISTANT", "Legal Assistant"),
                            ("CONSULTANT", "Consultant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "assigned_date",
                    models.DateField(auto_now_add=True, verbose_name="Assigned Date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="cases.case",
                        verbose_name="Case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Team Member",
                "verbose_name_plural": "Case Team Members",
                "ordering": ["case", "role"],
                "unique_together": {("case", "user", "role")},
            },
        ),
    ]
