# Generated by Django 5.0.7 on 2025-05-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_court_practicearea_alter_case_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='Check Date')),
                ('check_source', models.CharField(choices=[('AUTOMATED', 'Automated Check'), ('MANUAL', 'Manual Check'), ('CLIENT_DISCLOSURE', 'Client Disclosure'), ('THIRD_PARTY', 'Third Party Information')], default='AUTOMATED', max_length=20, verbose_name='Check Source')),
                ('parties_checked', models.JSONField(default=list, help_text='List of parties checked for conflicts', verbose_name='Parties Checked')),
                ('conflicts_found', models.BooleanField(default=False, verbose_name='Conflicts Found')),
                ('conflict_details', models.JSONField(blank=True, help_text='Details of any conflicts found', null=True, verbose_name='Conflict Details')),
                ('resolution_status', models.CharField(choices=[('NO_CONFLICT', 'No Conflict Found'), ('POTENTIAL_CONFLICT', 'Potential Conflict Identified'), ('CONFLICT_WAIVED', 'Conflict Waived'), ('CONFLICT_UNRESOLVED', 'Conflict Unresolved'), ('DECLINED', 'Representation Declined Due to Conflict')], default='NO_CONFLICT', max_length=20, verbose_name='Resolution Status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolution Date')),
                ('waiver_document', models.FileField(blank=True, null=True, upload_to='conflict_waivers/', verbose_name='Waiver Document')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_checks', to='cases.case', verbose_name='Case')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_conflict_checks', to=settings.AUTH_USER_MODEL, verbose_name='Checked By')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflict_checks', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Conflict Check',
                'verbose_name_plural': 'Conflict Checks',
                'ordering': ['-check_date'],
                'indexes': [models.Index(fields=['case', 'check_date'], name='cases_confl_case_id_8994c8_idx'), models.Index(fields=['conflicts_found', 'resolution_status'], name='cases_confl_conflic_1c043a_idx')],
            },
        ),
    ]
