# Generated by Django 5.0.7 on 2025-05-03 19:35

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_client_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_line1',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line2',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=core.fields.EncryptedCharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=core.fields.EncryptedCharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=core.fields.EncryptedCharField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=core.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=core.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=core.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ssn_last_four',
            field=core.fields.EncryptedCharField(blank=True, max_length=4, verbose_name='Last 4 of SSN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=core.fields.EncryptedCharField(blank=True, max_length=100, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=core.fields.EncryptedCharField(blank=True, max_length=50, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=core.fields.EncryptedCharField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='first_name',
            field=core.fields.EncryptedCharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='last_name',
            field=core.fields.EncryptedCharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='mobile',
            field=core.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='notes',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=core.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
