# Generated by Django 5.0.4 on 2025-04-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bar_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Bar Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biography"),
        ),
        migrations.AddField(
            model_name="user",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Hourly Rate",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Mobile Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="practice_areas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Practice Areas"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ATTORNEY", "Attorney"),
                    ("PARALEGAL", "Paralegal"),
                    ("LEGAL_ASSISTANT", "Legal Assistant"),
                    ("ADMIN", "Administrator"),
                    ("CLIENT", "Client"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=False, verbose_name="Is Client"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_lawyer",
            field=models.BooleanField(default=False, verbose_name="Is Lawyer"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
    ]
