# Generated by Django 5.0.7 on 2025-05-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bar_number_user_bio_user_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFASetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100, verbose_name='Secret Key')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='MFA Enabled')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Backup Codes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_setup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
