# Generated by Django 5.0.4 on 2025-04-26 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_court_practicearea_alter_case_options_and_more"),
        ("documents", "0002_rename_upload_date_document_uploaded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Document Tag",
                "verbose_name_plural": "Document Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTagged",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged Document",
                "verbose_name_plural": "Tagged Documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="document_templates/", verbose_name="Template File"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PLEADING", "Pleading"),
                            ("MOTION", "Motion"),
                            ("BRIEF", "Brief"),
                            ("CORRESPONDENCE", "Correspondence"),
                            ("CONTRACT", "Contract"),
                            ("AGREEMENT", "Agreement"),
                            ("EVIDENCE", "Evidence"),
                            ("DISCOVERY", "Discovery"),
                            ("DEPOSITION", "Deposition"),
                            ("EXHIBIT", "Exhibit"),
                            ("FORM", "Form"),
                            ("MEMO", "Memo"),
                            ("NOTE", "Note"),
                            ("REPORT", "Report"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="document_date",
            field=models.DateField(
                blank=True,
                help_text="The date on the document itself",
                null=True,
                verbose_name="Document Date",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, editable=False, null=True, verbose_name="File Size"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                blank=True, editable=False, max_length=50, verbose_name="File Type"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_latest_version",
            field=models.BooleanField(default=True, verbose_name="Latest Version"),
        ),
        migrations.AddField(
            model_name="document",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Private documents are only visible to staff, not clients",
                verbose_name="Private",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="Document can be used as a template for generating new documents",
                verbose_name="Template",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified At"),
        ),
        migrations.AddField(
            model_name="document",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newer_version",
                to="documents.document",
                verbose_name="Previous Version",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("FINAL", "Final"),
                    ("FILED", "Filed"),
                    ("EXECUTED", "Executed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Version"),
        ),
        migrations.AlterField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="cases.case",
                verbose_name="Case",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PLEADING", "Pleading"),
                    ("MOTION", "Motion"),
                    ("BRIEF", "Brief"),
                    ("CORRESPONDENCE", "Correspondence"),
                    ("CONTRACT", "Contract"),
                    ("AGREEMENT", "Agreement"),
                    ("EVIDENCE", "Evidence"),
                    ("DISCOVERY", "Discovery"),
                    ("DEPOSITION", "Deposition"),
                    ("EXHIBIT", "Exhibit"),
                    ("FORM", "Form"),
                    ("MEMO", "Memo"),
                    ("NOTE", "Note"),
                    ("REPORT", "Report"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Document Type",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="case_documents/", verbose_name="File"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded By",
            ),
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="documents.documentcategory",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documentcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["case", "-uploaded_at"], name="documents_d_case_id_0bbc2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "-uploaded_at"],
                name="documents_d_documen_b91311_idx",
            ),
        ),
        migrations.AddField(
            model_name="documenttagged",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documenttagged",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.documenttag",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documenttagged",
            unique_together={("document", "tag")},
        ),
    ]
