# Generated by Django 5.0.7 on 2025-05-03 19:11

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_conflictcheck'),
        ('documents', '0003_documenttag_documenttagged_documenttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={},
        ),
        migrations.CreateModel(
            name='SensitiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('document_type', models.CharField(choices=[('PLEADING', 'Pleading'), ('MOTION', 'Motion'), ('BRIEF', 'Brief'), ('CORRESPONDENCE', 'Correspondence'), ('CONTRACT', 'Contract'), ('AGREEMENT', 'Agreement'), ('EVIDENCE', 'Evidence'), ('DISCOVERY', 'Discovery'), ('DEPOSITION', 'Deposition'), ('EXHIBIT', 'Exhibit'), ('FORM', 'Form'), ('MEMO', 'Memo'), ('NOTE', 'Note'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Document Type')),
                ('sensitivity_level', models.CharField(choices=[('CONFIDENTIAL', 'Confidential'), ('PRIVILEGED', 'Privileged'), ('RESTRICTED', 'Restricted'), ('TOP_SECRET', 'Top Secret')], default='CONFIDENTIAL', max_length=20, verbose_name='Sensitivity Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('encryption_salt', models.BinaryField(null=True, verbose_name='Encryption Salt')),
                ('file', core.fields.EncryptedFileField(salt_field='encryption_salt', upload_to='encrypted_documents/', verbose_name='Encrypted File')),
                ('file_size', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='File Size')),
                ('file_type', models.CharField(blank=True, editable=False, max_length=50, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_latest_version', models.BooleanField(default=True, verbose_name='Latest Version')),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='accessible_sensitive_documents', to=settings.AUTH_USER_MODEL, verbose_name='Authorized Users')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_documents', to='cases.case', verbose_name='Case')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_versions', to='documents.document', verbose_name='Parent Document')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_version', to='documents.sensitivedocument', verbose_name='Previous Version')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sensitive_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Sensitive Document',
                'verbose_name_plural': 'Sensitive Documents',
                'ordering': ['-uploaded_at'],
                'permissions': [('view_any_sensitive_document', 'Can view any sensitive document'), ('upload_sensitive_document', 'Can upload sensitive documents')],
                'indexes': [models.Index(fields=['case', '-uploaded_at'], name='documents_s_case_id_df8b61_idx'), models.Index(fields=['sensitivity_level'], name='documents_s_sensiti_d5cce8_idx')],
            },
        ),
    ]
