# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='model_type',
            field=models.CharField(choices=[('gemma_3', 'Gemma 3'), ('gemma_2', 'Gemma 2'), ('llama_3', 'Llama 3'), ('mistral', 'Mistral'), ('ollama', 'Ollama'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('together', 'Together AI'), ('replicate', 'Replicate'), ('huggingface', 'Hugging Face'), ('cohere', 'Cohere'), ('gpt4free', 'GPT4Free'), ('other', 'Other')], default='openai', max_length=20, verbose_name='Model Type'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='deployment_type',
            field=models.CharField(choices=[('local', 'Local Deployment'), ('containerized', 'Containerized'), ('api', 'API Service'), ('vllm', 'vLLM Deployment'), ('ollama', 'Ollama Local'), ('lm_studio', 'LM Studio')], default='api', max_length=20, verbose_name='Deployment Type'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Model Version'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='api_key_name',
            field=models.CharField(blank=True, help_text="e.g., 'Authorization' or 'x-api-key'", max_length=50, verbose_name='API Key Name/Header'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='organization_id',
            field=models.CharField(blank=True, help_text='For OpenAI organization ID', max_length=100, null=True, verbose_name='Organization ID'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='top_p',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Top P'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='frequency_penalty',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Frequency Penalty'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='presence_penalty',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Presence Penalty'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this model is free to use', verbose_name='Is Free'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='cost_per_1k_tokens',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Cost per 1K tokens'),
        ),
    ]
