# Generated by Django 5.0.4 on 2025-04-26 00:19

from django.db import migrations
from django.utils import timezone
import datetime


def set_default_timestamps(apps, schema_editor):
    """
    Set default timestamps for existing records.
    This is a no-op migration since we're using --fake
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0002_aisettings_alter_llmmodel_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_timestamps),
    ]
