# Generated by Django 5.0.4 on 2025-04-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0003_auto_20250426_0219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
    ]
