# Generated by Django 5.0.7 on 2025-05-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_update_llm_model_fields'),
        ('ai_services', '0007_add_missing_fields_to_vectorstore'),
    ]

    operations = [
    ]
